---
- hosts: all

  vars:
    useComposer: true

  handlers:

  - name: restart iptables
    service: name=iptables state=restarted

  - name: restart httpd
    service: name=httpd state=restarted

  tasks: 

  - name: copy firewall template
    copy: src=templates/etc/sysconfig/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=0600
    notify: restart iptables

  - name: Install http
    yum: pkg={{ item }} state=installed
    with_items:
      - httpd

  - name: Copy govready minisite
    copy: src=vendor/govready/govready-html dest=/var/www/ owner=apache group=apache mode=755
    notify: restart httpd

  - name: Copy httpd-govready.conf for govready-html mini web site
    copy: src=vendor/govready/templates/httpd-govready.conf dest=/etc/httpd/conf.d/httpd-govready.conf
    notify: restart httpd

  - name: Ensure Apache running
    service: name=httpd state=started enabled=yes

  - name: Install git
    yum: pkg=git state=installed

# Install project specific software

  - name: Install build prequisites
    yum: pkg={{ item }} state=installed
    with_items:
      - make 
      - gcc
    sudo: True

  - name: Add epel RPM repository CentOS 6
    shell: su -c 'rpm -Uvh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm'

