---
- hosts: all

  vars:
    useComposer: true

  handlers:

  - name: restart iptables
    service: name=iptables state=restarted

  - name: restart httpd
    service: name=httpd state=restarted

  tasks: 

  - name: copy firewall template
    copy: src=templates/etc/sysconfig/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=0600
    notify: restart iptables

  - name: Install http
    yum: pkg={{ item }} state=installed
    with_items:
      - httpd

  - name: Copy default virtual server
    copy: src=templates/etc/httpd/conf.d/govready.conf dest=/etc/httpd/conf.d/govready.conf
    notify: restart httpd

  - name: Ensure Apache running
    service: name=httpd state=started enabled=yes

#  - name: Install git
#    yum: pkg=git state=installed

  - name: Copy default virtual server
    copy: src=templates/etc/httpd/conf.d/10-app.conf dest=/etc/httpd/conf.d/10-app.conf
    notify: restart httpd

# Install project specific software

#  - name: Install build prequisites
#    yum: pkg={{ item }} state=installed
#    with_items:
#      - make 
#      - gcc
#     sudo: True
#
#
#  - name: Add epel RPM repository CentOS 6
#    shell: su -c 'rpm -Uvh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm'

